CREATE TABLE lectures
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    teacher_id INTEGER,
    CONSTRAINT pk_lectures PRIMARY KEY (id)
);

CREATE TABLE user_lectures
(
    lecture_id INTEGER NOT NULL,
    user_id     INTEGER NOT NULL
);

CREATE TABLE users
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    identity_no VARCHAR(11),
    name        VARCHAR(255),
    surname     VARCHAR(255),
    gender      VARCHAR(255),
    urole       VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_identity_no UNIQUE (identity_no);

ALTER TABLE lectures
    ADD CONSTRAINT FK_LECTURES_ON_TEACHER FOREIGN KEY (teacher_id) REFERENCES users (id);

ALTER TABLE user_lectures
    ADD CONSTRAINT fk_uselec_on_lecture FOREIGN KEY (lecture_id) REFERENCES lectures (id);

ALTER TABLE user_lectures
    ADD CONSTRAINT fk_uselec_on_user FOREIGN KEY (user_id) REFERENCES users (id);